version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: prop-types
    versions:
    - 15.7.2
